feat(tests): add a test to add and remove plugins
coffee-tools/coffee pull request #158
Opened 2023-06-26 14:12 UTC by tareknaser360

2023-06-26 15:01 UTC, vincenzopalazzo requested changes

2023-06-26 15:01 UTC, vincenzopalazzo commented on tests/src/coffee_integration_tests.rs
> +    manager.coffee().rm_remote("lightningd").await.unwrap();
```suggestion
    manager.coffee().rm_remote("lightningd").await.unwrap();
```

put `"lightningd"` in a variable

2023-06-26 15:01 UTC, vincenzopalazzo commented on tests/src/coffee_integration_tests.rs
> +    let remotes = result.remotes.expect("remotes not found");
```suggestion
    let remotes = result.remotes.unwrap();
```

2023-06-26 15:01 UTC, vincenzopalazzo commented on tests/src/coffee_integration_tests.rs
> +    assert_eq!(remotes.len(), 0, "Unexpected number of remote repositories");
print the debug version of the remotes as I suggested in some previous line

2023-06-26 15:01 UTC, vincenzopalazzo commented on tests/src/coffee_integration_tests.rs
> +    assert_eq!(result.plugins.len(), 0, "Unexpected number of plugins");
print the debug version of the result as suggested before

2023-06-26 15:04 UTC, vincenzopalazzo commented on tests/src/coffee_integration_tests.rs
> +    assert_eq!(result.plugins.len(), 2, "Unexpected number of plugins");
Please print the debug version of the result

2023-06-28 12:13 UTC, tareknaser360 commented on tests/src/coffee_integration_tests.rs
> +    assert_eq!(remotes.len(), 1, "Unexpected number of remote repositories");
There is no method `is_ok` for `result` or `remotes` but we can print the debug version of `remotes`

2023-07-05 08:32 UTC, vincenzopalazzo commented
Rebased on top of master

2023-07-05 12:06 UTC, vincenzopalazzo approved these changes

2023-07-05 12:07 UTC, merged