Deprecate the nurse command and add a test
coffee-tools/coffee pull request #173
Opened 2023-07-15 21:43 UTC by tareknaser360

e51181172ba221ed944917b1d0eb57aac82022fd modifies the current test framework to allow to run a lightning node in any network specified in the test itself. 
-  previously we could only run lightning in `regtest`

49548f0c247b19491aa56fcf41eba826bc14922f adds a new test to mimic the issue where coffee fails to install the same plugin in 2 different networks.

Related issue: #172

2023-07-15 21:55 UTC, vincenzopalazzo requested changes
Very nice organisation and a lovely job.

I left some comments, also if there are any big issue

2023-07-15 21:55 UTC, vincenzopalazzo commented on coffee_testing/src/cln.rs
> +    pub async fn with_params(params: &str, network: String) -> anyhow::Result<Self> {
use `network: &str` so you can pass a literal string

2023-07-15 21:55 UTC, vincenzopalazzo commented on tests/src/coffee_httpd_integration_tests.rs
> +    let mut cln = Node::tmp("regtest".to_string()).await.unwrap();
then you can use just `Node::tmp("regtest")`

2023-07-15 21:55 UTC, vincenzopalazzo commented on tests/src/coffee_plugin_integration_tests.rs
> +    let mut cln = Node::with_params(&format!("--plugin={plugin_path}"), "regtest".to_string())
same in this file

2023-07-15 21:55 UTC, vincenzopalazzo commented on tests/src/coffee_integration_tests.rs
> +    };
we can assert on the dir? and make sure that you are running coffee on the same directory.

2023-07-15 21:55 UTC, vincenzopalazzo commented
This was the bug that we are looking for right?

```
coffee_1  | failures:
coffee_1  | 
coffee_1  | ---- coffee_integration_tests::install_plugin_in_two_networks stdout ----
coffee_1  | thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CoffeeError { code: 1, msg: "plugin `summary` are not present inside the repositories" }', tests/src/coffee_integration_tests.rs:358:10
coffee_1  | stack backtrace:
coffee_1  |    0: rust_begin_unwind
```

2023-07-15 22:20 UTC, tareknaser360 commented
> This was the bug that we are looking for right?

Yes. And by the way if we try to add `lightningd` as a remote repository for the `testnet`, it fails because it already exists in the `repositories` folder.
We need a way to separate coffee configurations based on network.

2023-07-15 22:23 UTC, vincenzopalazzo commented
>We need a way to separate coffee configurations based on network.

we need just a way to keep the coffee repositories network independent

2023-07-16 00:02 UTC, vincenzopalazzo approved these changes

2023-07-16 00:02 UTC, merged