chore(change-table-label): change table label from "Affected repositories" to "Action"
coffee-tools/coffee pull request #272
Opened 2024-04-17 08:33 UTC by Anyitechs

This PR addresses @tareknaser and @vincenzopalazzo suggestion in [#239 (comment](https://github.com/coffee-tools/coffee/pull/239#discussion_r1563209333))

Closes #268

2024-04-17 14:19 UTC, vincenzopalazzo commented
Coffee has the best documentation that I ever written, please read the commit style https://coffee-docs.netlify.app/contributing-to-coffee

2024-04-17 22:19 UTC, vincenzopalazzo commented on coffee_cmd/src/coffee_term/command_show.rs
> +            term::format::bold(String::from("Action")),
`Affected` sounds a really good one

2024-04-17 22:20 UTC, vincenzopalazzo requested changes
One thing is hard in coding, and it is naming things 😄 

After that ping me and we merge the PR

2024-04-17 22:20 UTC, vincenzopalazzo commented on coffee_cmd/src/coffee_term/command_show.rs
> +            term::format::bold(String::from("Action")),
```suggestion
            term::format::bold(String::from("Affected")),
```

thanks @tareknaser for the suggestion

2024-04-18 09:57 UTC, Anyitechs commented
> Coffee has the best documentation that I ever written, please read the commit style https://coffee-docs.netlify.app/contributing-to-coffee

Thank you @vincenzopalazzo for sharing the link. Recent commits are following the style guide now.

2024-04-18 12:10 UTC, tareknaser approved these changes

2024-05-15 08:24 UTC, merged